spring:
  datasource:
    url: jdbc:mysql://localhost:3306/likeflower?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1111
  jpa:
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
jwt:
  secret: MyScret
